cf_visualiser_/cf_visualiser_/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from login import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('search/', include('visualise.urls')),

    path('compare/', include('compare.urls')),

    path('contact_us/', views.contact_us, name='contact'),

    path('', views.index, name='index'),
    path('login/', include('login.urls')),
    path('logout/', views.user_logout, name='logout'),
]

cf_visualiser_/login/urls.py
from django.conf.urls import url, include
from django.urls import path
from login import views

# SET THE NAMESPACE!
app_name = 'login'

urlpatterns=[
    path('register/',views.register, name='register'),
    path('user_login/',views.user_login, name='user_login'),
] 

cf_visualiser_/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> {% block title %}  {% endblock %} </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
    {% load static %}
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
    
  </head>
  <body>
    
    <nav class="navbar navbar-default navbar-static-top " >
      <div class="container">
        <ul class="nav navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}

          <li><a class="navbar-brand" href="{% url 'index' %}">Codeforces Visualiser</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

          {% if not user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'login:register' %}">Register</a></li> 
          {% endif %}

          {# Some logic on what to display for last item#}

          {% if user.is_authenticated %}
            <li><a href="{% url 'search' %}">Search Handle</a></li>
            <li><a href="{% url 'compare' %}">Compare</a></li>
            <li><a href="{% url 'timetable' %}">Time-Table</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login:user_login' %}">Login</a></li>
          {% endif %}

          <li><a href="{% url 'contact' %}">Contact Us</a></li>
        </ul>
      </div>
    </nav>
    
    <div class="container">
    {% block content %}

    {% endblock %}
    </div>

    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
      Copyright &copy;
      <span class="year"></span> Codeforces Visualiser
    </footer>

  </body>
</html>

cf_visualiser_/templates/invalid_handle_compare.html
{% extends 'base.html' %}

{% block title %}
CF-Vis | Error
{% endblock %}

{% block content %}
    
    <h3>The handle(s) you entered seemed to be invalid.</h3>
	<h3>Please Try Again.</h3>

{% endblock %}

cf_visualiser_/templates/invalid_handle_search.html
{% extends 'base.html' %}

{% block title %}
    CF-Vis | Error
{% endblock %}

{% block content %}
    
	<h3>The handle(s) you tried to enter are invalid.</h3>
	<h3>Please Try Again.</h3>

{% endblock %}